services:
  - type: web
    name: code-share
    env: docker
    branch: main
    dockerfilePath: Dockerfile
    envVars:
      - key: REDIS_HOST
        value: ${REDIS_HOST}
      - key: REDIS_PORT
        value: ${REDIS_PORT}
      - key: REDIS_PASSWORD
        value: ${REDIS_PASSWORD}
